### ISSUE TITLE
feature: model, migrations 관련

### ISSUE THREAD

**Issue by JaeHyuckSa** [Django-Wanted-Internship-3-Team/repo2_restaurant_recommend#2]
##  이슈 내용
> 이슈 내용 작성
model, migrations 관련 이슈는 해당 이슈에 할당

<br>

**Comment by saJaeHyukc** [comment]
<img width="928" alt="image" src="https://github.com/Django-Wanted-Internship-3-Team/repo_2_restaurant_recommend/assets/104830931/8ebf169b-eb49-4d75-b2af-a4220e21e759">

**Comment by saJaeHyukc** [comment]
<img width="759" alt="image" src="https://github.com/Django-Wanted-Internship-3-Team/repo_2_restaurant_recommend/assets/104830931/d1c6b250-e058-4f87-a604-50973e8089aa">
